[package]
name = "nova-assembler"
version = "0.1.0"
edition = "2021"
authors = ["mazziechai"]
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
